server {
    listen 80;

    location /api/books/ {
        rewrite ^/api/books/(.*)$ /books/$1 break;
        proxy_pass http://listings-api:3001;
    }

    location = /api/books {
        rewrite ^/api/books$ /books break;
        proxy_pass http://listings-api:3001;
    }

    location /api/warehouse/ {
        rewrite ^/api/warehouse/(.*)$ /warehouse/$1 break;
        proxy_pass http://warehouse-api:3002;
    }

    location = /api/warehouse {
        rewrite ^/api/warehouse$ /warehouse break;
        proxy_pass http://warehouse-api:3002;
    }

    location /api/orders/ {
        rewrite ^/api/orders/(.*)$ /orders/$1 break;
        proxy_pass http://orders-api:3003;
    }

    location = /api/orders {
        rewrite ^/api/orders$ /orders break;
        proxy_pass http://orders-api:3003;
    }

    location /api/docs/swagger.json {
        proxy_pass http://docs-server:3004/docs/swagger.json;
    }

    location /api/docs {
        proxy_pass http://docs-server:3004/docs;
    }

    location /api/openapi.json {
        proxy_pass http://docs-server:3004/openapi.json;
    }

    location / {
        proxy_pass http://front-end:9080/;
    }
}
