/* tslint:disable */
/* eslint-disable */
/**
 * McMasterful Books APIs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateOrder200Response,
  CreateOrderRequest,
  FulfillOrderRequest,
  OrderDto,
  PlaceBooksOnShelf200Response,
} from '../models/index';
import {
    CreateOrder200ResponseFromJSON,
    CreateOrder200ResponseToJSON,
    CreateOrderRequestFromJSON,
    CreateOrderRequestToJSON,
    FulfillOrderRequestFromJSON,
    FulfillOrderRequestToJSON,
    OrderDtoFromJSON,
    OrderDtoToJSON,
    PlaceBooksOnShelf200ResponseFromJSON,
    PlaceBooksOnShelf200ResponseToJSON,
} from '../models/index';

export interface CreateOrderOperationRequest {
    createOrderRequest: CreateOrderRequest;
}

export interface FulfillOrderOperationRequest {
    orderId: string;
    fulfillOrderRequest: FulfillOrderRequest;
}

export interface GetOrderRequest {
    orderId: string;
}

/**
 * 
 */
export class OrdersApi extends runtime.BaseAPI {

    /**
     */
    async createOrderRaw(requestParameters: CreateOrderOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateOrder200Response>> {
        if (requestParameters['createOrderRequest'] == null) {
            throw new runtime.RequiredError(
                'createOrderRequest',
                'Required parameter "createOrderRequest" was null or undefined when calling createOrder().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/orders`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateOrderRequestToJSON(requestParameters['createOrderRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateOrder200ResponseFromJSON(jsonValue));
    }

    /**
     */
    async createOrder(requestParameters: CreateOrderOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateOrder200Response> {
        const response = await this.createOrderRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async fulfillOrderRaw(requestParameters: FulfillOrderOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PlaceBooksOnShelf200Response>> {
        if (requestParameters['orderId'] == null) {
            throw new runtime.RequiredError(
                'orderId',
                'Required parameter "orderId" was null or undefined when calling fulfillOrder().'
            );
        }

        if (requestParameters['fulfillOrderRequest'] == null) {
            throw new runtime.RequiredError(
                'fulfillOrderRequest',
                'Required parameter "fulfillOrderRequest" was null or undefined when calling fulfillOrder().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/orders/{orderId}/fulfill`.replace(`{${"orderId"}}`, encodeURIComponent(String(requestParameters['orderId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: FulfillOrderRequestToJSON(requestParameters['fulfillOrderRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PlaceBooksOnShelf200ResponseFromJSON(jsonValue));
    }

    /**
     */
    async fulfillOrder(requestParameters: FulfillOrderOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PlaceBooksOnShelf200Response> {
        const response = await this.fulfillOrderRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getOrderRaw(requestParameters: GetOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OrderDto>> {
        if (requestParameters['orderId'] == null) {
            throw new runtime.RequiredError(
                'orderId',
                'Required parameter "orderId" was null or undefined when calling getOrder().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/orders/{orderId}`.replace(`{${"orderId"}}`, encodeURIComponent(String(requestParameters['orderId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OrderDtoFromJSON(jsonValue));
    }

    /**
     */
    async getOrder(requestParameters: GetOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OrderDto> {
        const response = await this.getOrderRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async listOrdersRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<OrderDto>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/orders`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(OrderDtoFromJSON));
    }

    /**
     */
    async listOrders(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<OrderDto>> {
        const response = await this.listOrdersRaw(initOverrides);
        return await response.value();
    }

}
