/* tslint:disable */
/* eslint-disable */
/**
 * McMasterful Books APIs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  PlaceBooksOnShelf200Response,
  PlaceBooksRequest,
  ShelfStock,
} from '../models/index';
import {
    PlaceBooksOnShelf200ResponseFromJSON,
    PlaceBooksOnShelf200ResponseToJSON,
    PlaceBooksRequestFromJSON,
    PlaceBooksRequestToJSON,
    ShelfStockFromJSON,
    ShelfStockToJSON,
} from '../models/index';

export interface FindBookOnShelfRequest {
    bookId: string;
}

export interface PlaceBooksOnShelfRequest {
    placeBooksRequest: PlaceBooksRequest;
}

/**
 * 
 */
export class WarehouseApi extends runtime.BaseAPI {

    /**
     */
    async findBookOnShelfRaw(requestParameters: FindBookOnShelfRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ShelfStock>>> {
        if (requestParameters['bookId'] == null) {
            throw new runtime.RequiredError(
                'bookId',
                'Required parameter "bookId" was null or undefined when calling findBookOnShelf().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/warehouse/books/{bookId}/locations`.replace(`{${"bookId"}}`, encodeURIComponent(String(requestParameters['bookId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ShelfStockFromJSON));
    }

    /**
     */
    async findBookOnShelf(requestParameters: FindBookOnShelfRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ShelfStock>> {
        const response = await this.findBookOnShelfRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async placeBooksOnShelfRaw(requestParameters: PlaceBooksOnShelfRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PlaceBooksOnShelf200Response>> {
        if (requestParameters['placeBooksRequest'] == null) {
            throw new runtime.RequiredError(
                'placeBooksRequest',
                'Required parameter "placeBooksRequest" was null or undefined when calling placeBooksOnShelf().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/warehouse/shelves`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PlaceBooksRequestToJSON(requestParameters['placeBooksRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PlaceBooksOnShelf200ResponseFromJSON(jsonValue));
    }

    /**
     */
    async placeBooksOnShelf(requestParameters: PlaceBooksOnShelfRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PlaceBooksOnShelf200Response> {
        const response = await this.placeBooksOnShelfRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
