/* tslint:disable */
/* eslint-disable */
/**
 * assignment-1
 * This is a template repository for the first assignment in BVD 103 at McMaster Continuing Education.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BookDto
 */
export interface BookDto {
    /**
     * 
     * @type {string}
     * @memberof BookDto
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof BookDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof BookDto
     */
    author: string;
    /**
     * 
     * @type {string}
     * @memberof BookDto
     */
    description: string;
    /**
     * 
     * @type {number}
     * @memberof BookDto
     */
    price: number;
    /**
     * 
     * @type {string}
     * @memberof BookDto
     */
    image: string;
    /**
     * 
     * @type {number}
     * @memberof BookDto
     */
    stock?: number;
}

/**
 * Check if a given object implements the BookDto interface.
 */
export function instanceOfBookDto(value: object): value is BookDto {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('author' in value) || value['author'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('price' in value) || value['price'] === undefined) return false;
    if (!('image' in value) || value['image'] === undefined) return false;
    return true;
}

export function BookDtoFromJSON(json: any): BookDto {
    return BookDtoFromJSONTyped(json, false);
}

export function BookDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BookDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'],
        'author': json['author'],
        'description': json['description'],
        'price': json['price'],
        'image': json['image'],
        'stock': json['stock'] == null ? undefined : json['stock'],
    };
}

export function BookDtoToJSON(value?: BookDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
        'author': value['author'],
        'description': value['description'],
        'price': value['price'],
        'image': value['image'],
        'stock': value['stock'],
    };
}

