/* tslint:disable */
/* eslint-disable */
/**
 * McMasterful Books APIs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FilterInput
 */
export interface FilterInput {
    /**
     * 
     * @type {number}
     * @memberof FilterInput
     */
    from?: number;
    /**
     * 
     * @type {number}
     * @memberof FilterInput
     */
    to?: number;
    /**
     * 
     * @type {string}
     * @memberof FilterInput
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof FilterInput
     */
    author?: string;
}

/**
 * Check if a given object implements the FilterInput interface.
 */
export function instanceOfFilterInput(value: object): value is FilterInput {
    return true;
}

export function FilterInputFromJSON(json: any): FilterInput {
    return FilterInputFromJSONTyped(json, false);
}

export function FilterInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): FilterInput {
    if (json == null) {
        return json;
    }
    return {
        
        'from': json['from'] == null ? undefined : json['from'],
        'to': json['to'] == null ? undefined : json['to'],
        'name': json['name'] == null ? undefined : json['name'],
        'author': json['author'] == null ? undefined : json['author'],
    };
}

export function FilterInputToJSON(value?: FilterInput | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'from': value['from'],
        'to': value['to'],
        'name': value['name'],
        'author': value['author'],
    };
}

