/* tslint:disable */
/* eslint-disable */
/**
 * assignment-1
 * This is a template repository for the first assignment in BVD 103 at McMaster Continuing Education.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FulfillmentItem } from './FulfillmentItem';
import {
    FulfillmentItemFromJSON,
    FulfillmentItemFromJSONTyped,
    FulfillmentItemToJSON,
} from './FulfillmentItem';

/**
 * 
 * @export
 * @interface FulfillOrderRequest
 */
export interface FulfillOrderRequest {
    /**
     * 
     * @type {Array<FulfillmentItem>}
     * @memberof FulfillOrderRequest
     */
    fulfillment: Array<FulfillmentItem>;
}

/**
 * Check if a given object implements the FulfillOrderRequest interface.
 */
export function instanceOfFulfillOrderRequest(value: object): value is FulfillOrderRequest {
    if (!('fulfillment' in value) || value['fulfillment'] === undefined) return false;
    return true;
}

export function FulfillOrderRequestFromJSON(json: any): FulfillOrderRequest {
    return FulfillOrderRequestFromJSONTyped(json, false);
}

export function FulfillOrderRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): FulfillOrderRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'fulfillment': ((json['fulfillment'] as Array<any>).map(FulfillmentItemFromJSON)),
    };
}

export function FulfillOrderRequestToJSON(value?: FulfillOrderRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'fulfillment': ((value['fulfillment'] as Array<any>).map(FulfillmentItemToJSON)),
    };
}

