/* tslint:disable */
/* eslint-disable */
/**
 * assignment-1
 * This is a template repository for the first assignment in BVD 103 at McMaster Continuing Education.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrderDto
 */
export interface OrderDto {
    /**
     * 
     * @type {string}
     * @memberof OrderDto
     */
    orderId: string;
    /**
     * Construct a type with a set of properties K of type T
     * @type {{ [key: string]: number; }}
     * @memberof OrderDto
     */
    books: { [key: string]: number; };
    /**
     * 
     * @type {boolean}
     * @memberof OrderDto
     */
    fulfilled?: boolean;
}

/**
 * Check if a given object implements the OrderDto interface.
 */
export function instanceOfOrderDto(value: object): value is OrderDto {
    if (!('orderId' in value) || value['orderId'] === undefined) return false;
    if (!('books' in value) || value['books'] === undefined) return false;
    return true;
}

export function OrderDtoFromJSON(json: any): OrderDto {
    return OrderDtoFromJSONTyped(json, false);
}

export function OrderDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderDto {
    if (json == null) {
        return json;
    }
    return {
        
        'orderId': json['orderId'],
        'books': json['books'],
        'fulfilled': json['fulfilled'] == null ? undefined : json['fulfilled'],
    };
}

export function OrderDtoToJSON(value?: OrderDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'orderId': value['orderId'],
        'books': value['books'],
        'fulfilled': value['fulfilled'],
    };
}

