/* tslint:disable */
/* eslint-disable */
/**
 * assignment-1
 * This is a template repository for the first assignment in BVD 103 at McMaster Continuing Education.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PlaceBooksRequest
 */
export interface PlaceBooksRequest {
    /**
     * 
     * @type {string}
     * @memberof PlaceBooksRequest
     */
    bookId: string;
    /**
     * 
     * @type {number}
     * @memberof PlaceBooksRequest
     */
    numberOfBooks: number;
    /**
     * 
     * @type {string}
     * @memberof PlaceBooksRequest
     */
    shelf: string;
}

/**
 * Check if a given object implements the PlaceBooksRequest interface.
 */
export function instanceOfPlaceBooksRequest(value: object): value is PlaceBooksRequest {
    if (!('bookId' in value) || value['bookId'] === undefined) return false;
    if (!('numberOfBooks' in value) || value['numberOfBooks'] === undefined) return false;
    if (!('shelf' in value) || value['shelf'] === undefined) return false;
    return true;
}

export function PlaceBooksRequestFromJSON(json: any): PlaceBooksRequest {
    return PlaceBooksRequestFromJSONTyped(json, false);
}

export function PlaceBooksRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlaceBooksRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'bookId': json['bookId'],
        'numberOfBooks': json['numberOfBooks'],
        'shelf': json['shelf'],
    };
}

export function PlaceBooksRequestToJSON(value?: PlaceBooksRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'bookId': value['bookId'],
        'numberOfBooks': value['numberOfBooks'],
        'shelf': value['shelf'],
    };
}

