/* tslint:disable */
/* eslint-disable */
/**
 * assignment-1
 * This is a template repository for the first assignment in BVD 103 at McMaster Continuing Education.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PlaceBooks200Response
 */
export interface PlaceBooks200Response {
    /**
     * 
     * @type {boolean}
     * @memberof PlaceBooks200Response
     */
    success: boolean;
}

/**
 * Check if a given object implements the PlaceBooks200Response interface.
 */
export function instanceOfPlaceBooks200Response(value: object): value is PlaceBooks200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    return true;
}

export function PlaceBooks200ResponseFromJSON(json: any): PlaceBooks200Response {
    return PlaceBooks200ResponseFromJSONTyped(json, false);
}

export function PlaceBooks200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlaceBooks200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
    };
}

export function PlaceBooks200ResponseToJSON(value?: PlaceBooks200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'success': value['success'],
    };
}

