/* tslint:disable */
/* eslint-disable */
/**
 * assignment-1
 * This is a template repository for the first assignment in BVD 103 at McMaster Continuing Education.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ShelfStockDto
 */
export interface ShelfStockDto {
    /**
     * 
     * @type {string}
     * @memberof ShelfStockDto
     */
    shelf: string;
    /**
     * 
     * @type {number}
     * @memberof ShelfStockDto
     */
    count: number;
}

/**
 * Check if a given object implements the ShelfStockDto interface.
 */
export function instanceOfShelfStockDto(value: object): value is ShelfStockDto {
    if (!('shelf' in value) || value['shelf'] === undefined) return false;
    if (!('count' in value) || value['count'] === undefined) return false;
    return true;
}

export function ShelfStockDtoFromJSON(json: any): ShelfStockDto {
    return ShelfStockDtoFromJSONTyped(json, false);
}

export function ShelfStockDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShelfStockDto {
    if (json == null) {
        return json;
    }
    return {
        
        'shelf': json['shelf'],
        'count': json['count'],
    };
}

export function ShelfStockDtoToJSON(value?: ShelfStockDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'shelf': value['shelf'],
        'count': value['count'],
    };
}

