/* tslint:disable */
/* eslint-disable */
/**
 * assignment-1
 * This is a template repository for the first assignment in BVD 103 at McMaster Continuing Education.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Stock200Response
 */
export interface Stock200Response {
    /**
     * 
     * @type {number}
     * @memberof Stock200Response
     */
    stock: number;
    /**
     * 
     * @type {string}
     * @memberof Stock200Response
     */
    bookId: string;
}

/**
 * Check if a given object implements the Stock200Response interface.
 */
export function instanceOfStock200Response(value: object): value is Stock200Response {
    if (!('stock' in value) || value['stock'] === undefined) return false;
    if (!('bookId' in value) || value['bookId'] === undefined) return false;
    return true;
}

export function Stock200ResponseFromJSON(json: any): Stock200Response {
    return Stock200ResponseFromJSONTyped(json, false);
}

export function Stock200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): Stock200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'stock': json['stock'],
        'bookId': json['bookId'],
    };
}

export function Stock200ResponseToJSON(value?: Stock200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'stock': value['stock'],
        'bookId': value['bookId'],
    };
}

