/* tslint:disable */
/* eslint-disable */
/**
 * McMasterful Books APIs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PlaceBooksOnShelf200Response
 */
export interface PlaceBooksOnShelf200Response {
    /**
     * 
     * @type {boolean}
     * @memberof PlaceBooksOnShelf200Response
     */
    success: boolean;
}

/**
 * Check if a given object implements the PlaceBooksOnShelf200Response interface.
 */
export function instanceOfPlaceBooksOnShelf200Response(value: object): value is PlaceBooksOnShelf200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    return true;
}

export function PlaceBooksOnShelf200ResponseFromJSON(json: any): PlaceBooksOnShelf200Response {
    return PlaceBooksOnShelf200ResponseFromJSONTyped(json, false);
}

export function PlaceBooksOnShelf200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlaceBooksOnShelf200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
    };
}

export function PlaceBooksOnShelf200ResponseToJSON(value?: PlaceBooksOnShelf200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'success': value['success'],
    };
}

