/* tslint:disable */
/* eslint-disable */
/**
 * assignment-1
 * This is a template repository for the first assignment in BVD 103 at McMaster Continuing Education.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BookDto,
  CreateOrUpdateBook200Response,
} from '../models/index';
import {
    BookDtoFromJSON,
    BookDtoToJSON,
    CreateOrUpdateBook200ResponseFromJSON,
    CreateOrUpdateBook200ResponseToJSON,
} from '../models/index';

export interface CreateOrUpdateBookRequest {
    bookDto: BookDto;
}

export interface DeleteBookRequest {
    id: string;
}

export interface GetBookRequest {
    id: string;
}

export interface ListBooksRequest {
    from?: number;
    to?: number;
    name?: string;
    author?: string;
}

/**
 * 
 */
export class BooksApi extends runtime.BaseAPI {

    /**
     */
    async createOrUpdateBookRaw(requestParameters: CreateOrUpdateBookRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateOrUpdateBook200Response>> {
        if (requestParameters['bookDto'] == null) {
            throw new runtime.RequiredError(
                'bookDto',
                'Required parameter "bookDto" was null or undefined when calling createOrUpdateBook().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/books`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BookDtoToJSON(requestParameters['bookDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateOrUpdateBook200ResponseFromJSON(jsonValue));
    }

    /**
     */
    async createOrUpdateBook(requestParameters: CreateOrUpdateBookRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateOrUpdateBook200Response> {
        const response = await this.createOrUpdateBookRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async deleteBookRaw(requestParameters: DeleteBookRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteBook().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/books/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async deleteBook(requestParameters: DeleteBookRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteBookRaw(requestParameters, initOverrides);
    }

    /**
     */
    async getBookRaw(requestParameters: GetBookRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BookDto>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getBook().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/books/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BookDtoFromJSON(jsonValue));
    }

    /**
     */
    async getBook(requestParameters: GetBookRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BookDto> {
        const response = await this.getBookRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async listBooksRaw(requestParameters: ListBooksRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<BookDto>>> {
        const queryParameters: any = {};

        if (requestParameters['from'] != null) {
            queryParameters['from'] = requestParameters['from'];
        }

        if (requestParameters['to'] != null) {
            queryParameters['to'] = requestParameters['to'];
        }

        if (requestParameters['name'] != null) {
            queryParameters['name'] = requestParameters['name'];
        }

        if (requestParameters['author'] != null) {
            queryParameters['author'] = requestParameters['author'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/books`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(BookDtoFromJSON));
    }

    /**
     */
    async listBooks(requestParameters: ListBooksRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<BookDto>> {
        const response = await this.listBooksRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
