/* tslint:disable */
/* eslint-disable */
/**
 * assignment-1
 * This is a template repository for the first assignment in BVD 103 at McMaster Continuing Education.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  PlaceBooks200Response,
  PlaceBooksRequest,
  ShelfStockDto,
  Stock200Response,
} from '../models/index';
import {
    PlaceBooks200ResponseFromJSON,
    PlaceBooks200ResponseToJSON,
    PlaceBooksRequestFromJSON,
    PlaceBooksRequestToJSON,
    ShelfStockDtoFromJSON,
    ShelfStockDtoToJSON,
    Stock200ResponseFromJSON,
    Stock200ResponseToJSON,
} from '../models/index';

export interface LocationsRequest {
    bookId: string;
}

export interface PlaceBooksOperationRequest {
    placeBooksRequest: PlaceBooksRequest;
}

export interface StockRequest {
    bookId: string;
}

/**
 * 
 */
export class WarehouseApi extends runtime.BaseAPI {

    /**
     */
    async locationsRaw(requestParameters: LocationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ShelfStockDto>>> {
        if (requestParameters['bookId'] == null) {
            throw new runtime.RequiredError(
                'bookId',
                'Required parameter "bookId" was null or undefined when calling locations().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/warehouse/books/{bookId}/locations`.replace(`{${"bookId"}}`, encodeURIComponent(String(requestParameters['bookId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ShelfStockDtoFromJSON));
    }

    /**
     */
    async locations(requestParameters: LocationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ShelfStockDto>> {
        const response = await this.locationsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async placeBooksRaw(requestParameters: PlaceBooksOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PlaceBooks200Response>> {
        if (requestParameters['placeBooksRequest'] == null) {
            throw new runtime.RequiredError(
                'placeBooksRequest',
                'Required parameter "placeBooksRequest" was null or undefined when calling placeBooks().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/warehouse/shelves`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PlaceBooksRequestToJSON(requestParameters['placeBooksRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PlaceBooks200ResponseFromJSON(jsonValue));
    }

    /**
     */
    async placeBooks(requestParameters: PlaceBooksOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PlaceBooks200Response> {
        const response = await this.placeBooksRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async stockRaw(requestParameters: StockRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Stock200Response>> {
        if (requestParameters['bookId'] == null) {
            throw new runtime.RequiredError(
                'bookId',
                'Required parameter "bookId" was null or undefined when calling stock().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/warehouse/books/{bookId}/stock`.replace(`{${"bookId"}}`, encodeURIComponent(String(requestParameters['bookId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => Stock200ResponseFromJSON(jsonValue));
    }

    /**
     */
    async stock(requestParameters: StockRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Stock200Response> {
        const response = await this.stockRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
